"""First commit

Revision ID: 47842be4e4cc
Revises: 
Create Date: 2023-11-18 13:09:03.735275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47842be4e4cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile',
    sa.Column('mobile_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('mobile_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('mobile_name')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('year_of_birth', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('mobile')
    # ### end Alembic commands ###
