"""changed unique constraints for user and mobile

Revision ID: a02a7a32a314
Revises: 4bcb0fd07d44
Create Date: 2023-12-01 16:20:23.074051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02a7a32a314'
down_revision: Union[str, None] = '4bcb0fd07d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UserAccount_user_name_key', 'UserAccount', type_='unique')
    op.create_unique_constraint(None, 'mobile', ['mobile_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mobile', type_='unique')
    op.create_unique_constraint('UserAccount_user_name_key', 'UserAccount', ['user_name'])
    # ### end Alembic commands ###
