"""added overallreview

Revision ID: f2e778c245e8
Revises: aa077aab6651
Create Date: 2023-11-28 21:51:46.600580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e778c245e8'
down_revision: Union[str, None] = 'aa077aab6651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useroverallreview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('mobile_ID', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['mobile_ID'], ['mobile.mobile_ID'], ),
    sa.ForeignKeyConstraint(['user_ID'], ['UserAccount.user_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_individual_reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_individual_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mobile_ID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('review', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mobile_ID'], ['mobile.mobile_ID'], name='user_individual_reviews_mobile_ID_fkey'),
    sa.ForeignKeyConstraint(['user_ID'], ['UserAccount.user_ID'], name='user_individual_reviews_user_ID_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_individual_reviews_pkey')
    )
    op.drop_table('useroverallreview')
    # ### end Alembic commands ###
